version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp
    overwrite: true
hooks: 
  ApplicationStop:
    - location: /scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/change_file.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 300
      runas: root

